@host = http://localhost:8080/fhir

@folder = ips

### Post fixed StructureMap which is not integrated in the implementation guide 
GET {{host}}/metadata


### Post data
POST {{host}}/ HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./{{folder}}/ips-data.json
